#!/usr/bin/python3.6

# Reference https://github.com/munin-monitoring/contrib/tree/master/plugins/varnish

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import json, sys
import subprocess
from aspects import varnish_aspects

class Monitor(object):
    aspects_munin = varnish_aspects
    varnish_stats = {}

    def __init__(self):
        varnishcommand=["varnishstat", "-j"]
        json_stats = subprocess.run(varnishcommand, stdout=subprocess.PIPE)
        self.varnish_stats = json.loads(json_stats.stdout)

    def getValues(self,monitor):
        for i in self.aspects_munin[monitor]["values"].keys():
            stats_key = "MAIN."+str(i)
            print('{0}.value {1}'.format(i, self.varnish_stats[stats_key]['value']))

    def getConfig(self,monitor):
        print("graph_category Varnish")
        print('graph_title {0}'.format(self.aspects_munin[monitor]["title"]))
        graph_param = ["order","scale","vlabel","args"]
        for i in graph_param:
            if i in self.aspects_munin[monitor].keys():
                print('graph_{0} {1}'.format(i, self.aspects_munin[monitor][i]))
        for j in self.aspects_munin[monitor]["values"].keys():
            stats_key = "MAIN."+str(j)
            print('{0}.label {1}'.format(j, self.varnish_stats[stats_key]['description']))
            for k in self.aspects_munin[monitor]["values"][j].keys():
                    print('{0}.{1} {2}'.format(j,k,self.aspects_munin[monitor]["values"][j][k]))

    def getSuggest(self):
        tomontor = ["backend_traffic","request_rate","transfer_rates","uptime","objects","threads","expunge"]
        for i in tomontor:
            print(i)

if __name__ == '__main__':
    element = sys.argv[0].split("varnish6_")
    if element[1]:
        varnish = Monitor()
        if len(sys.argv) < 2:
            varnish.getValues(element[1])
        elif sys.argv[1] == "config":
            varnish.getConfig(element[1])
        elif sys.argv[1] == "suggest":
            varnish.getSuggest()
        else:
            print("Wrong Args")
    else:
        print('{0} suggest'.format(sys.argv[0]))
